/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelosvistas;

/**
 *
 * @author Coloo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBarra = new javax.swing.JMenuBar();
        mSalir = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        jMenuVuelos = new javax.swing.JMenu();
        mVuelos = new javax.swing.JMenuItem();
        jMenuCiudades = new javax.swing.JMenu();
        mCiudades = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        mClientes = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenu();
        mCompras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de vuelos");
        setSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuBarra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBarra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBarra.setMaximumSize(new java.awt.Dimension(390, 32773));
        jMenuBarra.setMinimumSize(new java.awt.Dimension(4, 4));

        mSalir.setText("Archivo");
        mSalir.setToolTipText("");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        mSalir.add(salir);

        jMenuBarra.add(mSalir);

        jMenuVuelos.setText("Vuelos");
        jMenuVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVuelosActionPerformed(evt);
            }
        });

        mVuelos.setText("Lista de vuelos");
        mVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVuelosActionPerformed(evt);
            }
        });
        jMenuVuelos.add(mVuelos);

        jMenuBarra.add(jMenuVuelos);

        jMenuCiudades.setText("Ciudades");

        mCiudades.setText("Lista de ciudades");
        mCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCiudadesActionPerformed(evt);
            }
        });
        jMenuCiudades.add(mCiudades);

        jMenuBarra.add(jMenuCiudades);

        jMenuClientes.setText("Clientes");

        mClientes.setText("Lista de clientes");
        mClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(mClientes);

        jMenuBarra.add(jMenuClientes);

        jMenuCompras.setText("Compras");

        mCompras.setText("Lista de compras");
        mCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mComprasActionPerformed(evt);
            }
        });
        jMenuCompras.add(mCompras);

        jMenuBarra.add(jMenuCompras);

        setJMenuBar(jMenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void mVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVuelosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaMaterias vm=new VistaMaterias();
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_mVuelosActionPerformed

    private void jMenuVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuVuelosActionPerformed

    private void mCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCiudadesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaInscripciones ins=new VistaInscripciones();
        ins.setVisible(true);
        escritorio.add(ins);
        escritorio.moveToFront(ins);
    }//GEN-LAST:event_mCiudadesActionPerformed

    private void mClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mClientesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaCargaNotas va=new VistaCargaNotas();
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
    }//GEN-LAST:event_mClientesActionPerformed

    private void mComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mComprasActionPerformed
        // TODO add your handling code here:

        escritorio.removeAll();
        escritorio.repaint();
        VistaAlumnosMaterias vm=new VistaAlumnosMaterias();
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_mComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBarra;
    private javax.swing.JMenu jMenuCiudades;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenu jMenuVuelos;
    private javax.swing.JMenuItem mCiudades;
    private javax.swing.JMenuItem mClientes;
    private javax.swing.JMenuItem mCompras;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem mVuelos;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
